/* eslint-disable no-console */
import { db } from "@/db";
import { matchbooks, projects } from "@/db/schema";

const matchbooksData = [
  {
    city: "Carmel",
    country: "USA",
    date: "2025-01-02",
    description: "The Inn at The Carmel Beach",
    established: "1925",
    id: "colonial-terrace-inn",
    primaryImage: "/matchbooks/1A.jpeg",
    secondaryImage: "/matchbooks/1B.jpeg",
    state: "CA",
    street: "San Antonio Between 12th & 13th",
    title: "Colonial Terrace Inn",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2025-01-02",
    description: "Come and Enjoy.",
    id: "new-york-worlds-fair",
    primaryImage: "/matchbooks/2A.jpeg",
    secondaryImage: "/matchbooks/2B.jpeg",
    state: "NY",
    street: "Flushing Meadows-Corona Park",
    title: "New York World's Fair",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2025-01-02",
    description: "RESTAURANT",
    id: "lawlers",
    primaryImage: "/matchbooks/3A.jpeg",
    secondaryImage: "/matchbooks/3B.jpeg",
    state: "NY",
    street: "95 LIBERTY ST.",
    title: "Lawler's",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2025-01-02",
    description: "",
    id: "hotel-gramercy-park",
    primaryImage: "/matchbooks/4A.jpeg",
    secondaryImage: "/matchbooks/4B.jpeg",
    state: "NY",
    street: "52 GRAMERCY PARK NORTH, EAST 21st STREET",
    title: "Hotel Gramercy Park",
  },
  {
    city: "Fulton",
    country: "USA",
    date: "2025-01-02",
    description: "HOME COOKING",
    id: "wallace-grill",
    primaryImage: "/matchbooks/6A.jpeg",
    secondaryImage: "/matchbooks/6B.jpeg",
    state: "NY",
    street: "125 Cayuga Street",
    title: "Wallace Grill",
  },
  {
    city: "St. Petersburg",
    country: "USA",
    date: "2025-01-02",
    description: "WORLD'S OLDEST GREYHOUND TRACK",
    id: "derby-lane",
    primaryImage: "/matchbooks/7A.jpeg",
    secondaryImage: "/matchbooks/7B.jpeg",
    state: "FL",
    title: "Derby Lane",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2025-02-12",
    description: "FREIGHT SERVICE",
    id: "early-birds",
    primaryImage: "/matchbooks/8A.jpeg",
    secondaryImage: "/matchbooks/8B.jpeg",
    state: "NY",
    title: "Early Birds",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2025-02-12",
    description: "Enoteca Iperbole",
    id: "roma-di-notte",
    primaryImage: "/matchbooks/9A.jpeg",
    secondaryImage: "/matchbooks/9B.jpeg",
    state: "NY",
    title: "Roma di Notte",
  },
  {
    city: "Caceres",
    country: "Spain",
    date: "2025-02-12",
    description: "",
    id: "hotel-residencia-alcantara",
    primaryImage: "/matchbooks/10A.jpeg",
    secondaryImage: "/matchbooks/10B.jpeg",
    street: "Av. Virgen de Guadalupe, 14",
    title: "Hotel-Residencia Alcantara",
  },
  {
    city: "Fulton",
    country: "USA",
    date: "2025-02-12",
    description: "The Finest Steak & Shore Dinners",
    id: "lock-restaurant",
    primaryImage: "/matchbooks/11A.jpeg",
    secondaryImage: "/matchbooks/11B.jpeg",
    state: "NY",
    title: "Lock Restaurant",
  },
  {
    country: "USA",
    date: "2025-02-12",
    description: "",
    id: "howard-johnsons-motor-lodges",
    primaryImage: "/matchbooks/12A.jpeg",
    secondaryImage: "/matchbooks/12B.jpeg",
    title: "Howard Johnson's Motor Lodges",
  },
  {
    city: "Hollywood",
    country: "USA",
    date: "2025-02-12",
    description: "FREE 5 x 7 PROFESSIONAL ENLARGEMENT",
    id: "hollywood-film-studios",
    primaryImage: "/matchbooks/13A.jpeg",
    secondaryImage: "/matchbooks/13B.jpeg",
    state: "CA",
    title: "Hollywood Film Studios",
  },
  {
    country: "USA",
    date: "2025-03-24",
    description: "Extremely Mild",
    id: "cavalier-cigarettes",
    primaryImage: "/matchbooks/14A.jpeg",
    secondaryImage: "/matchbooks/14B.jpeg",
    title: "Cavalier Cigarettes",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2025-03-24",
    description: "FLY WITH THE NAVY",
    id: "naval-aviation-cadet-selection-board",
    primaryImage: "/matchbooks/15A.jpeg",
    secondaryImage: "/matchbooks/15B.jpeg",
    state: "NY",
    street: "120 BROADWAY",
    title: "Naval Aviation Cadet Selection Board",
  },
  {
    country: "USA",
    date: "2025-03-24",
    description: "FOR COUGHS DUE TO COLDS",
    id: "ff-lozenges",
    primaryImage: "/matchbooks/16A.jpeg",
    secondaryImage: "/matchbooks/16B.jpeg",
    title: "F&F Lozenges",
  },
  {
    country: "USA",
    date: "2025-03-24",
    description: "Wings for All America",
    id: "piper",
    primaryImage: "/matchbooks/17A.jpeg",
    secondaryImage: "/matchbooks/17B.jpeg",
    title: "Piper Cub",
  },
  {
    country: "USA",
    date: "2025-03-24",
    description: "SERVING AMERICA IN THE ARMY, NAVY AND C.A.P.",
    id: "piper-cub",
    primaryImage: "/matchbooks/18A.jpeg",
    secondaryImage: "/matchbooks/18B.jpeg",
    title: "Piper Cub",
  },
  {
    country: "USA",
    date: "2025-03-24",
    description: "growth-promoting additive",
    id: "nixon-feeds",
    primaryImage: "/matchbooks/19A.jpeg",
    secondaryImage: "/matchbooks/19B.jpeg",
    state: "NE",
    title: "Nixon Feeds",
  },
  {
    city: "Fulton",
    country: "USA",
    date: "2025-05-04",
    description: "FINE FOODS and ALL LEGAL BEVERAGES",
    id: "harmony-grill",
    primaryImage: "/matchbooks/21A.jpeg",
    secondaryImage: "/matchbooks/21B.jpeg",
    state: "NY",
    street: "West 1st and Leitch St.",
    title: "The Harmony Grill",
  },
  {
    city: "Syracuse",
    country: "USA",
    date: "2025-05-04",
    description: "DAYLITE LOBBY",
    id: "jefferson-clinton-hotel",
    primaryImage: "/matchbooks/22A.jpeg",
    secondaryImage: "/matchbooks/22B.jpeg",
    state: "NY",
    title: "Jefferson Clinton Hotel",
  },
  {
    city: "Whiteface",
    country: "USA",
    date: "2025-05-04",
    description: "",
    id: "whiteface-inn",
    primaryImage: "/matchbooks/23A.jpeg",
    secondaryImage: "/matchbooks/23B.jpeg",
    state: "NY",
    title: "Whiteface Inn",
  },
  {
    country: "USA",
    date: "2025-05-04",
    description: "Helps Build Strong Bodies 12 Ways!",
    id: "wonder-bread",
    primaryImage: "/matchbooks/24A.jpeg",
    secondaryImage: "/matchbooks/24B.jpeg",
    title: "Wonder Bread",
  },
  {
    country: "USA",
    date: "2025-05-04",
    description: "",
    id: "the-great-way",
    primaryImage: "/matchbooks/25A.jpeg",
    secondaryImage: "/matchbooks/25B.jpeg",
    title: "The Great Way",
  },
  {
    country: "USA",
    date: "2025-05-04",
    description: "We waited till you came. All the others had '5 O'clock Shadow'!",
    id: "gem-blades",
    primaryImage: "/matchbooks/26A.jpeg",
    secondaryImage: "/matchbooks/26B.jpeg",
    title: "Gem Blades",
  },
  {
    country: "USA",
    date: "2025-06-14",
    description: "AMERICA'S FAVORITE",
    id: "champion-spark-plugs",
    primaryImage: "/matchbooks/27A.jpeg",
    secondaryImage: "/matchbooks/27B.jpeg",
    title: "Champion Spark Plugs",
  },
  {
    city: "Fulton",
    country: "USA",
    date: "2025-06-14",
    description: "HOME COOKING THAT YOU WILL LIKE",
    id: "community-diner",
    primaryImage: "/matchbooks/28A.jpeg",
    secondaryImage: "/matchbooks/28B.jpeg",
    state: "NY",
    street: "Cor. First & State Sts.",
    title: "Community Diner",
  },
  {
    city: "Fulton",
    country: "USA",
    date: "2025-06-14",
    description: "READING SUPER-CLEANED ANTHRACITE",
    id: "john-w-pratt",
    primaryImage: "/matchbooks/29A.jpeg",
    secondaryImage: "/matchbooks/29B.jpeg",
    state: "NY",
    street: "120 PRATT ST.",
    title: "John W. Pratt",
  },
  {
    city: "New York",
    country: "USA",
    date: "2025-06-14",
    description: "Chew TOPPS Gum - A Quality Chewing Gum Made With Only Natural Flavors",
    id: "topps-gum",
    primaryImage: "/matchbooks/30A.jpeg",
    secondaryImage: "/matchbooks/30B.jpeg",
    state: "NY",
    title: "TOPPS Gum",
  },
  {
    city: "Wadsworth",
    country: "USA",
    date: "2025-06-14",
    description: "Exciting panorama of 45 colorful animal stamps from 20 different countries. All are genuine postage stamps. Thrill to elephants rampaging through a sea of grass. A bull gorilla lumbers out of a rain forest before your eyes! See a doe nuzzling her fawn. Marvel at wolves and leopards on the prowl. Get these and many other fantastic wild animal stamps FREE with coupon inside.",
    id: "fabulous-wildlife-stamp-collection",
    primaryImage: "/matchbooks/31A.jpeg",
    secondaryImage: "/matchbooks/31B.jpeg",
    state: "OH",
    title: "Fabulous Wildlife Stamp Collection",
  },
  {
    city: "Speculator",
    country: "USA",
    date: "2025-06-14",
    description: "for modern living get a GOULDS WATER SYSTEM",
    id: "sydney-griffiths",
    primaryImage: "/matchbooks/32A.jpeg",
    secondaryImage: "/matchbooks/32B.jpeg",
    state: "NY",
    title: "Sydney Griffiths",
  },
  {
    city: "Dallas",
    country: "USA",
    date: "2025-07-25",
    description: "American Association for Respiratory Therapy",
    id: "aart",
    primaryImage: "/matchbooks/33A.jpeg",
    secondaryImage: "/matchbooks/33B.jpeg",
    state: "TX",
    street: "1720 Regal Row",
    title: "AART",
  },
  {
    city: "Rome",
    country: "USA",
    date: "2025-07-25",
    description: "Choice Wines, Liquors, Cordials",
    id: "james-f-larkin",
    primaryImage: "/matchbooks/34A.jpeg",
    secondaryImage: "/matchbooks/34B.jpeg",
    state: "NY",
    street: "118 N. Washington Street",
    title: "James F. Larkin",
  },
  {
    country: "USA",
    date: "2025-07-25",
    description: "DO YOU KNOW A SPACE CADET?",
    id: "space-cadet",
    primaryImage: "/matchbooks/35A.jpeg",
    secondaryImage: "/matchbooks/35B.jpeg",
    title: "Space Cadet",
  },
  {
    city: "Toccoa",
    country: "USA",
    date: "2025-07-25",
    description: "SWIM for FUN and HEALTH",
    id: "pecks-motel-restaurant",
    primaryImage: "/matchbooks/36A.jpeg",
    secondaryImage: "/matchbooks/36B.jpeg",
    state: "GA",
    title: "Peck's Motel & Restaurant",
  },
  {
    country: "USA",
    date: "2025-07-25",
    description: "PRESERVES & PROTECTS FOOD",
    id: "safety-edge-diamond-waxed-paper",
    primaryImage: "/matchbooks/37A.jpeg",
    secondaryImage: "/matchbooks/37B.jpeg",
    title: "Safety-Edge Diamond Waxed Paper",
  },
  {
    city: "St. Louis",
    country: "USA",
    date: "2025-07-25",
    description: "350 ROOMS WITH BATH & SHOWER, CIRCULATING ICE WATER, PARKING. Visit the beautiful Claridge Lounge. Center of Wholesale District.",
    id: "claridge-hotel",
    primaryImage: "/matchbooks/38A.jpeg",
    secondaryImage: "/matchbooks/38B.jpeg",
    state: "MO",
    street: "Locust at Eighteenth",
    title: "Claridge Hotel",
  },
  {
    city: "San Francisco",
    country: "USA",
    date: "2025-09-04",
    description: "500 ROOMS",
    id: "hotel-whitcomb",
    primaryImage: "/matchbooks/39A.jpeg",
    secondaryImage: "/matchbooks/39B.jpeg",
    state: "CA",
    street: "CIVIC CENTER - MARKET AT 8th",
    title: "Hotel Whitcomb",
  },
  {
    city: "Easton",
    country: "USA",
    date: "2025-09-04",
    description: "Pride of the Eastern Shore",
    id: "tidewater-inn",
    primaryImage: "/matchbooks/40A.jpeg",
    secondaryImage: "/matchbooks/40B.jpeg",
    state: "MD",
    title: "The Tidewater Inn",
  },
  {
    city: "Montreal",
    country: "Canada",
    date: "2025-09-04",
    description: "SALON-BAR",
    id: "motel-metropole",
    primaryImage: "/matchbooks/41A.jpeg",
    secondaryImage: "/matchbooks/41B.jpeg",
    title: "Motel Metropole",
  },
  {
    city: "Syracuse",
    country: "USA",
    date: "2025-09-04",
    description: "Veal Pasta Steaks",
    id: "casa-di-copani",
    primaryImage: "/matchbooks/42A.jpeg",
    secondaryImage: "/matchbooks/42B.jpeg",
    state: "NY",
    title: "Casa Di Copani",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2025-09-04",
    description: "VIA LINCOLN TUNNEL TO NEW YORK",
    id: "blue-coach",
    primaryImage: "/matchbooks/43A.jpeg",
    secondaryImage: "/matchbooks/43B.jpeg",
    state: "NY",
    title: "Blue Coach",
  },
  {
    city: "Sarasota",
    country: "USA",
    date: "2025-09-04",
    description: "Waterfront Restaurant and Bar. AAA Approved. On Little Sarasota Bay.",
    id: "turtles",
    primaryImage: "/matchbooks/44A.jpeg",
    secondaryImage: "/matchbooks/44B.jpeg",
    state: "FL",
    street: "8875 Midnight Pass Rd.",
    title: "Turtles",
  },
  {
    country: "USA",
    date: "2025-10-15",
    description: "September 3-12, 1982. Horse Racing Pari-Mutuel Betting: July 28 - August 29, October 6 - November 7, 1982.",
    id: "nebraska-state-fair",
    primaryImage: "/matchbooks/45A.jpeg",
    secondaryImage: "/matchbooks/45B.jpeg",
    state: "NE",
    title: "Nebraska State Fair",
  },
  {
    country: "USA",
    date: "2025-10-15",
    description: "",
    id: "manger-hotels-motor-inns",
    primaryImage: "/matchbooks/46A.jpeg",
    secondaryImage: "/matchbooks/46B.jpeg",
    title: "Manger Hotels & Motor Inns",
  },
  {
    city: "New York",
    country: "USA",
    date: "2025-10-15",
    description: "OUR FIRST DUTY. WE MUST WIN! Buy MORE WAR BONDS * STAMPS",
    id: "war-bonds-stamps",
    primaryImage: "/matchbooks/47A.jpeg",
    secondaryImage: "/matchbooks/47B.jpeg",
    state: "NY",
    title: "War Bonds & Stamps",
  },
  {
    city: "Eagle Bay",
    country: "USA",
    date: "2025-10-15",
    description: "MEALS you'd be proud to serve YOURSELF",
    id: "toboggan-inn",
    primaryImage: "/matchbooks/48A.jpeg",
    secondaryImage: "/matchbooks/48B.jpeg",
    state: "NY",
    title: "Toboggan Inn",
  },
  {
    city: "Washington",
    country: "USA",
    date: "2025-10-15",
    description: "A LITTLE BIT OF PARIS. FRENCH - AMERICAN Restaurant. IN THE HEART OF THE NATION'S CAPITAL.",
    id: "bonats",
    primaryImage: "/matchbooks/49A.jpeg",
    secondaryImage: "/matchbooks/49B.jpeg",
    state: "DC",
    street: "1022 VERMONT AVE., N. W.",
    title: "Bonats",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2025-10-15",
    description: "I DON'T GET NO RESPECT. Entertainment Nightly.",
    id: "dangerfields",
    primaryImage: "/matchbooks/51A.jpeg",
    secondaryImage: "/matchbooks/51B.jpeg",
    state: "NY",
    street: "1118 First Ave. (Bet. 61st & 62nd Sts.)",
    title: "Dangerfield's",
  },
  {
    city: "Cincinnati",
    country: "USA",
    date: "2025-11-26",
    description: "ON ROUTES NO.25-27-41-47-50-52-74",
    id: "broadway-hotel",
    primaryImage: "/matchbooks/52A.jpeg",
    secondaryImage: "/matchbooks/52B.jpeg",
    state: "OH",
    street: "4th & Broadway",
    title: "Broadway Hotel",
  },
  {
    country: "USA",
    date: "2025-11-26",
    description: "CLOSE COVER BEFORE STRIKING MATCH",
    id: "california-zephyr",
    primaryImage: "/matchbooks/53A.jpeg",
    secondaryImage: "/matchbooks/53B.jpeg",
    title: "California Zephyr",
  },
  {
    city: "Ste. Agathe Des Monts",
    country: "Canada",
    date: "2025-11-26",
    description: "All year round resort",
    id: "the-laurentide-inn",
    primaryImage: "/matchbooks/54A.jpeg",
    secondaryImage: "/matchbooks/54B.jpeg",
    state: "QC",
    title: "The Laurentide Inn",
  },
  {
    country: "USA",
    date: "2025-11-26",
    description: "Airways Hotel, Seaway Hotel, Sea Crest Supper Club, Towne House Hotel in Buffalo, N.Y. Airways Inn in Milwaukee, Wisc.",
    id: "airways-hotel-chain",
    primaryImage: "/matchbooks/55A.jpeg",
    secondaryImage: "/matchbooks/55B.jpeg",
    title: "Airways Hotel Chain",
  },
  {
    country: "USA",
    date: "2025-11-26",
    description: "America's favorite ...by far",
    id: "hunts-tomato-sauce",
    primaryImage: "/matchbooks/56A.jpeg",
    secondaryImage: "/matchbooks/56B.jpeg",
    title: "Hunt's Tomato Sauce",
  },
  {
    city: "Buffalo",
    country: "USA",
    date: "2025-11-26",
    description: "Sold at Loblaws. Product of Shield Foods, Inc. ONE POUND NET.",
    id: "orchard-park-coffee",
    primaryImage: "/matchbooks/57A.jpeg",
    secondaryImage: "/matchbooks/57B.jpeg",
    state: "NY",
    title: "Orchard Park Coffee",
  },
  {
    country: "USA",
    date: "2026-01-06",
    description: "The 30 Minute Utility Light that burns in wind or rain. The Perfect Warning Signal Repair Light",
    id: "utilite",
    primaryImage: "/matchbooks/58A.jpeg",
    secondaryImage: "/matchbooks/58B.jpeg",
    title: "Utilite",
  },
  {
    city: "Bloomington",
    country: "USA",
    date: "2026-01-06",
    description: "Compliments. Funk's G Hybrid. SEEDSMEN TO THE WORLD.",
    id: "funk-seeds-international",
    primaryImage: "/matchbooks/59A.jpeg",
    secondaryImage: "/matchbooks/59B.jpeg",
    state: "IL",
    street: "1300 W. Washington St., Box 911",
    title: "Funk Seeds International, Inc.",
  },
  {
    city: "Chicago",
    country: "USA",
    date: "2026-01-06",
    description: "United Service Organizations. The Young Men's Christian Associations, The National Catholic Community Service, The Salvation Army, The Young Women's Christian Associations, The Jewish Welfare Board, The National Travelers Aid Association.",
    id: "uso",
    primaryImage: "/matchbooks/60A.jpeg",
    secondaryImage: "/matchbooks/60B.jpeg",
    state: "IL",
    title: "USO",
  },
  {
    country: "USA",
    date: "2026-01-06",
    description: "New and Used Books, Complete Student Supply Service",
    id: "university-book-store",
    primaryImage: "/matchbooks/61A.jpeg",
    secondaryImage: "/matchbooks/61B.jpeg",
    street: "Across From Union Building",
    title: "University Book Store",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2026-01-06",
    description: "Harlem's most 'Swelelegant' Dining Salon. CATERING TO BANQUETS DINNERS AND TEAS. Orders Delivered. Walter Brown, Mgr. Phone AUD. 3-7694.",
    id: "anchor-inn",
    primaryImage: "/matchbooks/62A.jpeg",
    secondaryImage: "/matchbooks/62B.jpeg",
    state: "NY",
    street: "2297 SEVENTH AVE. (COR. 135TH ST.)",
    title: "Anchor Inn",
  },
  {
    city: "New York City",
    country: "USA",
    date: "2026-01-06",
    description: "",
    established: "1876",
    id: "cavanaghs",
    primaryImage: "/matchbooks/63A.jpeg",
    secondaryImage: "/matchbooks/63B.jpeg",
    state: "NY",
    street: "260 West 23rd Street",
    title: "Cavanagh's",
  },
  {
    country: "USA",
    date: "2026-01-06",
    description: "CATHARTIC LAXATIVE. STARTS WHERE OTHERS LEAVE OFF. See Inside For Trial Size Offer. Beneficial in the treatment of RHEUMATISM, HEADACHES, ECZEMA, KIDNEY, LIVER, BOWELS, MORNING-AFTER. At your nearest DRUG STORE.",
    id: "tsb-saline",
    primaryImage: "/matchbooks/64A.jpeg",
    secondaryImage: "/matchbooks/64B.jpeg",
    title: "T.S.B. Saline",
  },
  {
    city: "Conesus Lake",
    country: "USA",
    date: "2026-01-06",
    description: "For the Prime of Your Life",
    id: "conesus-inn",
    primaryImage: "/matchbooks/65A.jpeg",
    secondaryImage: "/matchbooks/65B.jpeg",
    state: "NY",
    street: "2170 East Lake Road",
    title: "Conesus Inn",
  },
  {
    country: "USA",
    date: "2026-01-06",
    description: "STRIKE-ON-BOX MATCHES",
    id: "copperhead",
    primaryImage: "/matchbooks/66A.jpeg",
    secondaryImage: "/matchbooks/66A.jpeg",
    title: "Copperhead",
  },
  {
    city: "San Simeon",
    country: "USA",
    date: "2026-01-06",
    description: "Aerial View of Hearst Castle",
    id: "hearst-castle",
    primaryImage: "/matchbooks/67A.jpeg",
    secondaryImage: "/matchbooks/67B.jpeg",
    state: "CA",
    title: "Hearst Castle",
  },
  {
    city: "Rochester",
    country: "USA",
    date: "2026-01-06",
    description: "Continental Cuisine",
    id: "rio-bamba",
    primaryImage: "/matchbooks/68A.jpeg",
    secondaryImage: "/matchbooks/68B.jpeg",
    state: "NY",
    street: "282 Alexander Street",
    title: "Rio Bamba",
  },
];

const exampleProjects = [
  {
    description:
      "A macOS menu bar app for managing multiple timezones and converting times. Made for personal use to help schedule meetings across timezones. Built for my personal needs working between New York and Melbourne timezones.",
    id: "timesync",
    projectType: "macOS App",
    title: "Timesync",
    url: "https://timesync.dolmios.com/",
    year: "2026",
  },
  {
    description:
      "A Stitches-like CSS-in-JS library with CSS variables for instant theme switching, built-in multi-theme support, and Next.js App Router integration. Type-safe, performant, and actively maintained.",
    id: "stoop",
    projectType: "CSS-in-JS Library",
    title: "Stoop",
    url: "https://stoop.dolmios.com/",
    year: "2026",
  },
  {
    description:
      "A companion UI component library for Stoop, providing pre-built, type-safe React components with built-in theming support. Ships with accessible, customizable components for rapid application development.",
    id: "stoop-ui",
    projectType: "UI Library",
    title: "Stoop UI",
    url: "https://www.npmjs.com/package/stoop-ui",
    year: "2026",
  },
  {
    description:
      "A comprehensive ESLint configuration for modern JavaScript and TypeScript projects. Features TypeScript support, React best practices, accessibility rules, Next.js optimization, and automatic project structure detection.",
    id: "eslint-config-dolmios",
    projectType: "ESLint Config",
    title: "ESLint Config",
    url: "https://github.com/dolmios/eslint-config-dolmios",
    year: "2022",
  },
  {
    description:
      "A comprehensive directory of short-term rental software helping vacation rental businesses discover, compare, and select the most suitable platforms. Features AI-powered recommendations and detailed platform comparisons.",
    id: "hoststack",
    projectType: "Web App",
    title: "HostStack",
    url: "https://hoststack.app/",
    year: "2025",
  },
  {
    description:
      "An open-source web-based UI component library for HostStack. Provides reusable components and design patterns for building consistent interfaces across the HostStack ecosystem.",
    id: "hoststack-ui",
    projectType: "UI Library",
    title: "HostStack UI",
    url: "https://github.com/hoststack/ui",
    year: "2025",
  },
  {
    description:
      "A curated film camera collection and online store delivering vintage cameras across Australia. Features carefully selected 35mm and medium format cameras that are personally tested and approved for use.",
    id: "artefact35",
    projectType: "E-Commerce",
    title: "Artefact35",
    url: "http://a35.dolmios.com/",
    year: "2016",
  },
  {
    description:
      "A React component library, designed for Consolia's internal projects and design system. Features modern design patterns, TypeScript-first development, light/dark mode theming, and comprehensive responsive utilities.",
    id: "consolia-ui",
    projectType: "UI Library",
    title: "Consolia UI",
    url: "https://github.com/consolia-io/ui",
    year: "2025",
  },
  {
    description:
      "Real-time NYC Alternate Side Parking tracking web app built with Next.js and Supabase. Features automatic ASP zone detection, parking session management with reminders, and visual map display of parking zones. Still working on this when I find time, mostly it's an experiment using NYC Open Data.",
    id: "sweeptime",
    projectType: "Web App",
    title: "Sweeptime",
    url: "https://github.com/dolmios/sweeptime",
    year: "2026",
  },
];

async function seed(): Promise<void> {
  try {
    // Clear existing data
    await db.delete(matchbooks);
    await db.delete(projects);

    // Insert matchbooks
    await db.insert(matchbooks).values(matchbooksData);

    // Insert example projects
    await db.insert(projects).values(exampleProjects);

    console.log("Seeded database with matchbooks and projects");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

// Run seed
seed()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
